// Facts below are summarized from the supplied résumé, not independently verified.
// Personal introductions are editorial draft copy. No inferred project URLs.
export const records = [
  { id: 'vinyl-sound', title: 'Vinyl & Sound', lines: ['Vinyl', '& Sound'], color: '#c7ad65', ink: '#25271d', short: 'Where engineering meets the ritual of listening.', intro: 'A record makes me slow down. I’m interested in what happens when the physical experience of music meets the tools we build to understand it.', subjects: 'Revinyl / Vinylize / VinylMind', stories: [
    ['Revinyl', 'Founder · Dec 2025–Sep 2026', 'A community project introducing young listeners to the culture and science of analog music, through educational writing, a digital album library, and shared listening sessions.'],
    ['Vinylize', 'Inventor · Jun–Aug 2026', 'An interactive physical simulation that turns MP3 and WAV audio into a virtual record. A three-dimensional groove view connects the sound to the geometry the virtual stylus reads.'],
    ['VinylMind', 'Inventor · Jul–Sep 2026 · Details pending', 'The résumé identifies an AI and signal-processing project for vinyl analysis and preservation. Its detailed description is unfinished; demonstrations and outcomes are still to be supplied.']
  ], media: 'A listening session, a favorite sleeve, or a Vinylize demonstration.' },
  { id: 'language-access', title: 'Language & Access', lines: ['Language', '& Access'], color: '#77a7b7', ink: '#122f40', short: 'Building a bridge between language and learning.', intro: 'Access begins with being able to understand. TayTranslator explores how a small, carefully built tool can help make learning resources more approachable.', subjects: 'TayTranslator / Offline tools', stories: [
    ['TayTranslator', 'Inventor · Jun 2025–Jun 2026', 'A Vietnamese–Tày translation system intended to support access to Vietnamese-language learning resources for ethnic minority communities.'],
    ['Designed around limited connectivity', 'Technical approach · Résumé summary', 'The project combines sentence retrieval, word alignment, and Viterbi decoding. The résumé describes an offline implementation that does not rely on an external API.'],
    ['Making the work understandable', 'Demonstration pending', 'A paired-language walkthrough will show the original text, the proposed translation, and the limits of the system. Translation examples and community feedback will be added after review.']
  ], media: 'An annotated translation walkthrough, with reviewed Vietnamese and Tày text.' },
  { id: 'community', title: 'Community', lines: ['Common', 'ground.'], color: '#c47151', ink: '#39251d', short: 'Learning together, and making room for others.', intro: 'The most useful technology starts with people. Community work gives me a reason to listen before I build, and to keep learning after a project leaves my hands.', subjects: 'Humanitas / The CodingBuddy', stories: [
    ['Humanitas', 'Founder · Mar 2025–present', 'A student-led initiative focused on technology access and digital skills in Bản Liền, Lào Cai. The résumé describes English and computer-skills classes, equipment support, and community workshops.'],
    ['The CodingBuddy', 'Inventor & lead tutor · Jan 2026–present', 'A programming education platform for learners aged 10–15. The résumé describes a project-based curriculum and directing profits toward educational support for ethnic minority communities.'],
    ['Stories behind the work', 'Reflection draft pending', 'This space will hold a specific moment from teaching or community work, in Nam’s own words. Participant photographs and quotations require permission before inclusion.']
  ], media: 'A permission-cleared photograph from a class or community workshop.' },
  { id: 'robotics', title: 'Robotics', lines: ['Think.', 'Build.', 'Repeat.'], color: '#8e9caf', ink: '#202c40', short: 'Code, iteration, and the people around the robot.', intro: 'Robotics makes an idea answer to the real world. A program has to work with friction, timing, sensors, and a team that is learning alongside it.', subjects: 'VEX / Kid Engineering / Robotics clubs', stories: [
    ['From code to competition', 'Main coder · Résumé summary', 'Robot programming, autonomous optimization, and competition strategy for VEX V5. The résumé lists a 2026 national Robot Skills Champion title and Innovate Award, plus World Championship qualification.'],
    ['Teaching the next iteration', 'Kid Engineering mentor · May–Aug 2026', 'Supported teams preparing for WRO 2026, working on sensor-based control, project development, and technical communication.'],
    ['A place to build together', 'Newton Robotics Club · Vice president', 'The résumé lists this role from November 2025. A detailed account of responsibilities, club photographs, and a robot demonstration are still to be added.']
  ], media: 'A robot test, a programming notebook, or competition footage.' },
  { id: 'research', title: 'Research', lines: ['Asking', 'better', 'questions.'], color: '#afa5c1', ink: '#332d44', short: 'Questions about access, infrastructure, and listening.', intro: 'I’m drawn to questions that sit between a technical system and the person using it: what makes access possible, and what does a system need to respect?', subjects: 'Rural technology access / Edge AI', stories: [
    ['Technology access in rural communities', 'Co-author · Publication listed in résumé', '“Engineering Analysis of Technology Accessibility and Infrastructure Enhancement Strategies for Improving Educational Access in Rural Communities.” The résumé lists publication in JITeCS; a citation and paper have not yet been supplied for verification.'],
    ['Emotion recognition during vinyl listening', 'Co-author · In progress as of Sep 2026', '“Real-Time Edge-Based Emotion Recognition in Vinyl Music Listening Using Attention-Based Deep Learning.” The résumé gives an August–October 2026 period and describes literature review and a proposed privacy-conscious edge framework.'],
    ['Evidence and limits', 'Source material pending', 'Paper links, publication metadata, methodology, and limitations belong here after review. Proposed models are not presented as deployed systems or validated outcomes.']
  ], media: 'A research diagram, annotated methodology, or verified paper excerpt.' },
  { id: 'experience', title: 'Experience & Leadership', lines: ['Learning', 'by doing.'], color: '#a1ad7d', ink: '#293525', short: 'Working with teams, from voice technology to STEM.', intro: 'I learn differently when an idea has to be shared, explained, and built with other people. These experiences stretch both my technical work and the way I contribute to a team.', subjects: 'VBEE / STEAMS / HKU & NTU', stories: [
    ['Voice technology at VBEE AITALK', 'Software engineering intern · Jun–Oct 2026', 'The résumé describes work on a Vietnamese article-reading browser extension, including content extraction and text-to-speech integration. Some product details remain unfinished in the source.'],
    ['STEAMS', 'Head of Expertise · Dec 2024–Feb 2026', 'Led academic content work for the STEM club at Hanoi–Amsterdam, coordinating educational materials and supporting workshops and exhibitions.'],
    ['Business and innovation with digitalisation', 'HKU Academy for the Talented & NTU · Jun 2026', 'Participated in an interdisciplinary program connecting business strategy and technology. The résumé describes a team proposal exploring AI-assisted brand-partnership analysis.']
  ], media: 'A team working session, approved product screen, or program reflection.' },
  { id: 'learning', title: 'Learning & Milestones', lines: ['Stay', 'curious.'], color: '#ddc78d', ink: '#49402d', short: 'The subjects, challenges, and milestones along the way.', intro: 'My interests don’t fit inside one subject. Language, mathematics, physics, and computer science give me different ways to ask a question and work toward an answer.', subjects: 'Education / Mathematics / Physics', stories: [
    ['Hanoi–Amsterdam High School for the Gifted', 'English honor class · 2024–2027', 'The supplied résumé lists English as the honor class, alongside interests and projects in computer science, physics, and engineering.'],
    ['Selected academic milestones', 'Scores reported in résumé', 'SAT 1570, IELTS 8.5, AP Calculus BC 5, and AP Physics C 4. These are résumé-sourced figures; certificates are not included in this prototype.'],
    ['Mathematics and physics', 'Selected honors · 2025–2026', 'The résumé lists a 2025 UKMT Senior Mathematical Challenge Gold Prize, a 2026 IAPhO Gold Medal, and a 2026 Continental Calculus League Asian Gold Medal. Supporting documents can be added later.']
  ], media: 'A notebook page, a school photograph, or selected certificates.' },
  { id: 'beyond', title: 'Beyond the Work', lines: ['The', 'long way', 'home.'], color: '#789e96', ink: '#193831', short: 'Long runs, small observations, and time away from a screen.', intro: 'There is room here for things that don’t need an outcome: a long run, a record played all the way through, or a moment I want to remember.', subjects: 'Running / Listening / Reflections', stories: [
    ['Finding a rhythm', 'Running · Résumé summary', 'The résumé includes half-marathon and trail-running participation, including the Tay Ho Half Marathon and Ecopark City Trail. Exact race dates will be checked before a final timeline is added.'],
    ['Away from the screen', 'Personal reflection · Draft', 'What does a long run make space for? This short reflection will be replaced with Nam’s own account of running, attention, and everyday life.'],
    ['A few things worth keeping', 'Photographs pending', 'A small, personal photo sequence will live here: ordinary places, objects, and moments. No stock photographs are presented as personal memories.']
  ], media: 'A personal photograph from a run, a quiet afternoon, or a favorite place.' }
];
